### PR TITLE
Fix T0Request update function to avoid unneeded documents update

### LINKED ISSUE #11304: Investigate why t0_request CouchDB database grows at a rate of 2GB/h
**Impact of the bug**
T0 WMAgent

**Describe the bug**
It's been a while that I noticed that the `t0_request` CouchDB is getting lots of updates, increasing the CouchDB database size and running database compaction non-stop. The data size is barely changing, but the data volume (including document updates) increases in a rate of 1GB every 30min, as one can see in this grafana plot:
https://monit-grafana.cern.ch/goto/9Uy9uN4Vk?orgId=11

**How to reproduce it**
Not sure

**Expected behavior**
We need to contact the T0 team and gather information on how the T0 agent is updating these documents.

This database contains a very basic workflow structure, which includes the workflow status and its transitions, e.g.:
https://cmsweb.cern.ch/couchdb/t0_request/Express_Run235284_StreamExpressCosmics

and as such, I would not expect more than 10 revisions (actually N statuses) for each workflow, but contrary to that, this example workflow had 230 revisions (updates!).

This needs to be investigated and the T0 agent changed such that it only updates the request document if it actually has any changes.

**Additional context and error message**
This needs to be done sooner than later

### PR DESCRIPTION
**Pull request by amaltaro**
Fixes #11304 

#### Status
ready

#### Description
This PR fixes the T0Request couchapp update function, ensuring that documents transitioning from/to the same request status are not updated. In other words, if a workflow needs to be updated from status AAA to AAA, the update function will simply skip the document update (hence, the document will keep the same revision number as it had before the update call).

In addition to that, improve the TaskArchiver log record such that we can see what was the outcome of the update call. 

Documentation: https://docs.couchdb.org/en/3.2.2-docs/ddocs/ddocs.html#update-functions

#### Is it backward compatible (if not, which system it affects?)
YES

#### Related PRs
None

#### External dependencies / deployment changes
In order to apply this patch to the T0 agent, the following set of commands is required:
1. Patch the couchapps area:
```
curl https://patch-diff.githubusercontent.com/raw/dmwm/WMCore/pull/11353.patch | patch -d apps/t0/data/couchapps/ -p 3
```
2. Patch the python code area
```
curl https://patch-diff.githubusercontent.com/raw/dmwm/WMCore/pull/11353.patch | patch -d apps/t0/lib/python3.8/site-packages/ -p 3
```
3. Push the up-to-date CouchApps (before starting all the components, but with CouchDB running):
```
$manage execute-agent wmagent-couchapp-init
```

### CODE REVIEW

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
Thanks to @germanfgv for running a replay with these changes in, we can see that documents are no longer continuously and unneded updated. Checking one workflow in local couchdb:
```
cmst0@vocms0500:/data/tier0/srv/wmagent/current $ curl localhost:5984/t0_request_local/Repack_Run360886_StreamALCALowPtJet_Tier0_REPLAY_2022_ID221031125321_v31125321
{"_id":"Repack_Run360886_StreamALCALowPtJet_Tier0_REPLAY_2022_ID221031125321_v31125321","_rev":"5-3b0fe29894435c6d45ead9a88baa1b6f","RequestName":"Repack_Run360886_StreamALCALowPtJet_Tier0_REPLAY_2022_ID221031125321_v31125321","Run":360886,"RequestStatus":"completed","RequestTransition":[{"Status":"new","UpdateTime":1667217240},{"Status":"Closed","UpdateTime":1667217287},{"Status":"Merge","UpdateTime":1667217800},{"Status":"completed","UpdateTime":1667218159}]}
```

the revision number is sound (5 updates in total), while with the buggy code it would be beyond 15 or so by now.

File: src/couchapps/T0Request/updates/updaterequest.js [hunk 1]
```diff
@@ -36,11 +36,11 @@ function(doc, req)
     function updateTransition(newStatus) {
     	
     	if (allowedStates.indexOf(newStatus) === -1) {
-    		return "not allowed state " + newStatus;
+    		return "Not allowed state: " + newStatus;
     	}
     	if (doc.RequestStatus && !isAllowedTransiton(doc.RequestStatus, newStatus)) {
     		// don't update the status just ignore
-    		return "not allowed transition " + doc.RequestStatus + " to " + newStatus;
+    		return "Not allowed transition, from " + doc.RequestStatus + " to " + newStatus;
```
Comment (vkuznet) [inline src/couchapps/T0Request/updates/updaterequest.js:43]: I always suggest to put quotes around status'es that it will increase readability especially if status is not integer data-type. For instance, if status is some sentences, e.g. 'status is ok' then reading full string will become more clear that status is shown in quotes.

**Comment by amaltaro** [comment]
@vkuznet Valentin, the javascript source code looks uglier, but it's easier on the client perspective. I updated the error message as you suggested. Please have another look.

**Review by vkuznet — APPROVED** [review]

**Comment by amaltaro** [comment]
@germanfgv as discussed during the WMCore meeting today. I would recommend to apply this patch to the T0 agents, it does require a stop of the components, stop of couch, apply the couchapps patch, start of couch, push up-to-date couchapps and start all the components. Please let us know via Slack if you need help with any of this.
