### PR TITLE
Discover the singularity container OS at runtime.

### LINKED ISSUE #11893: CleanupJobs fail due to xrdfs shared library version mismatch.
**Impact of the bug**
Cleanup jobs

**Describe the bug**
Following a report from T0 team we checked and confirmed the presence of the following error [1] from cleanup jobs also for the production WMAgents.  The origin of the problem seem to be a shared library mismatch between the `xrdfs` executable  accessible through `cvmfs` and the runtime environment of the job. Possibly due to a job scram arch  mismatch or wrong `LD_LIBRARY_PATH` value at runtime. 
   

**How to reproduce it**
Not clear yet

**Expected behavior**
To not be able to use `xrdfs` from `cvmfs` at any moment.

**Additional context and error message**

Just for logging purposes, I add here a single command to run any of the singularity containers we run at runtime and available through `/cvmfs/`:
```
[user@lxplus988]$ "/cvmfs/oasis.opensciencegrid.org/mis/singularity/current/bin/singularity" -vvv -d  exec --home "/tmp/glide_bBZiCh":/srv --pwd /srv  --ipc --contain  --pid --bind "/cvmfs,/etc/hosts,/etc/localtime"  "/cvmfs/singularity.opensciencegrid.org/cmssw/cms:rhel8-itb" /bin/bash
``` 

[1]

```
2024-02-09 13:25:06,861:INFO:DeleteMgr:Local Stage Out Implementation to be used is:xrdcp
Local Stage Out PNN to be used is T2_CH_CERN
Local Stage Out Catalog to be used is trivialcatalog_file:/cvmfs/cms.cern.ch/SITECONF/T2_CH_CERN/PhEDEx/storage.xml?protocol=eos
Trivial File Catalog has been loaded:
        lfn-to-pfn: protocol=eos path-match-re=/+store/mc/HCtest/GenericTTbar/GEN-SIM-RECO/CMSSW_7_0_4_START70_V7-v1/(.*) result=root://eospps.cern.ch//eos/pps/mw-test/phedex/store/mc/HCtest/GenericTTbar/GEN-SIM-RECO/CMSSW_7_0_4_START70_V7-v1/$1
        lfn-to-pfn: protocol=eos path-match-re=/+store/(.*) result=root://eoscms.cern.ch//eos/cms/store/$1
        lfn-to-pfn: protocol=P5xrootd path-match-re=/+store/(.*) result=root://eoscmshlt.cern.ch//eos/cms/store/$1
        lfn-to-pfn: protocol=xrootd path-match-re=/+store/(.*) result=root://xrootd-cms.infn.it//store/$1
        lfn-to-pfn: protocol=srmv2 path-match-re=/+store/user/(.*) result=srm://srm-eoscms.cern.ch:8443/srm/v2/server?SFN=/eos/cms/store/user/$1
        lfn-to-pfn: protocol=srmv2 path-match-re=/+store/group/(.*) result=srm://srm-eoscms.cern.ch:8443/srm/v2/server?SFN=/eos/cms/store/group/$1
        pfn-to-lfn: protocol=eos path-match-re=root://eoscms.cern.ch//eos/cms/store/(.*) result=/store/$1
        pfn-to-lfn: protocol=P5xrootd path-match-re=root://eoscmshlt.cern.ch//eos/cms/store/(.*) result=/store/$1
        pfn-to-lfn: protocol=srmv2 path-match-re=.*\?SFN=/eos/cms(.*) result=$1

2024-02-09 13:25:06,861:INFO:DeleteMgr:==>Working on file: /store/unmerged/Run3Winter24Reco/GluGlutoHHto4B_kl-2p45_kt-1p00_c2-0p00_TuneCP5_13p6TeV_powheg-pythia8/AODSIM/133X_mcRun3_2024_realistic_v9-v3/2820000/27ec44a5-1e43-4073-b827-ca54c3d40e9e.root
2024-02-09 13:25:06,861:INFO:DeleteMgr:===> Attempting To Delete.
2024-02-09 13:25:06,862:INFO:DeleteMgr:LFN to PFN match made:
LFN: /store/unmerged/Run3Winter24Reco/GluGlutoHHto4B_kl-2p45_kt-1p00_c2-0p00_TuneCP5_13p6TeV_powheg-pythia8/AODSIM/133X_mcRun3_2024_realistic_v9-v3/2820000/27ec44a5-1e43-4073-b827-ca54c3d40e9e.root
PFN: root://eoscms.cern.ch//eos/cms/store/unmerged/Run3Winter24Reco/GluGlutoHHto4B_kl-2p45_kt-1p00_c2-0p00_TuneCP5_13p6TeV_powheg-pythia8/AODSIM/133X_mcRun3_2024_realistic_v9-v3/2820000/27ec44a5-1e43-4073-b827-ca54c3d40e9e.root

2024-02-09 13:25:06,909:INFO:StageOutImpl:Command exited with status: 1
Output message: stdout: 
stderr: xrdfs: /cvmfs/cms.cern.ch/COMP/slc7_amd64_gcc630/external/gcc/6.3.0/lib64/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by xrdfs)
xrdfs: /cvmfs/cms.cern.ch/COMP/slc7_amd64_gcc630/external/gcc/6.3.0/lib64/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by /lib64/libXrdCl.so.3)

2024-02-09 13:25:06,909:ERROR:StageOutImpl:Exception During Stage Out:
Command exited non-zero, ExitCode:1
Output: stdout: 
stderr: xrdfs: /cvmfs/cms.cern.ch/COMP/slc7_amd64_gcc630/external/gcc/6.3.0/lib64/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by xrdfs)
xrdfs: /cvmfs/cms.cern.ch/COMP/slc7_amd64_gcc630/external/gcc/6.3.0/lib64/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by /lib64/libXrdCl.so.3)
 
2024-02-09 13:25:07,002:ERROR:DeleteMgr:Failed to delete file: root://eoscms.cern.ch//eos/cms/store/unmerged/Run3Winter24Reco/GluGlutoHHto4B_kl-2p45_kt-1p00_c2-0p00_TuneCP5_13p6TeV_powheg-pythia8/AODSIM/133X_mcRun3_2024_realistic_v9-v3/2820000/27ec44a5-1e43-4073-b827-ca54c3d40e9e.root
2024-02-09 13:25:07,003:ERROR:DeleteMgr:===> Local file deletion failure. Exception:
<@========== WMException Start ==========@>
Exception Class: StageOutError
Message: Command exited non-zero, ExitCode:1
Output: stdout: 
stderr: xrdfs: /cvmfs/cms.cern.ch/COMP/slc7_amd64_gcc630/external/gcc/6.3.0/lib64/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by xrdfs)
xrdfs: /cvmfs/cms.cern.ch/COMP/slc7_amd64_gcc630/external/gcc/6.3.0/lib64/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by /lib64/libXrdCl.so.3)
 
        ClassName : None
        ModuleName : WMCore.Storage.StageOutError
        MethodName : __init__
        ClassInstance : None
        FileName : /srv/job/WMCore.zip/WMCore/Storage/StageOutError.py
        LineNumber : 32
        ErrorNr : 0
        Command : xrdfs eoscms.cern.ch rm /eos/cms/store/unmerged/Run3Winter24Reco/GluGlutoHHto4B_kl-2p45_kt-1p00_c2-0p00_TuneCP5_13p6TeV_powheg-pythia8/AODSIM/133X_mcRun3_2024_realistic_v9-v3/2820000/27ec44a5-1e43-4073-b827-ca54c3d40e9e.root
        ExitCode : 1
        ErrorCode : 60311
        ErrorType : GeneralStageOutFailure
        Protocol : xrdcp
        LFN : /store/unmerged/Run3Winter24Reco/GluGlutoHHto4B_kl-2p45_kt-1p00_c2-0p00_TuneCP5_13p6TeV_powheg-pythia8/AODSIM/133X_mcRun3_2024_realistic_v9-v3/2820000/27ec44a5-1e43-4073-b827-ca54c3d40e9e.root
        TargetPFN : root://eoscms.cern.ch//eos/cms/store/unmerged/Run3Winter24Reco/GluGlutoHHto4B_kl-2p45_kt-1p00_c2-0p00_TuneCP5_13p6TeV_powheg-pythia8/AODSIM/133X_mcRun3_2024_realistic_v9-v3/2820000/27ec44a5-1e43-4073-b827-ca54c3d40e9e.root

Traceback: 

<@---------- WMException End ----------@>
2024-02-09 13:25:07,005:ERROR:DeleteFiles:General failure in StageOut for DeleteFiles. Error: <@========== WMException Start ==========@>
Exception Class: StageOutFailure
Message: Unable to delete file:
/store/unmerged/Run3Winter24Reco/GluGlutoHHto4B_kl-2p45_kt-1p00_c2-0p00_TuneCP5_13p6TeV_powheg-pythia8/AODSIM/133X_mcRun3_2024_realistic_v9-v3/2820000/27ec44a5-1e43-4073-b827-ca54c3d40e9e.root
        ClassName : None
        ModuleName : WMCore.Storage.StageOutError
        MethodName : __init__
        ClassInstance : None
        FileName : /srv/job/WMCore.zip/WMCore/Storage/StageOutError.py
        LineNumber : 32
        ErrorNr : 0
        LFN : /store/unmerged/Run3Winter24Reco/GluGlutoHHto4B_kl-2p45_kt-1p00_c2-0p00_TuneCP5_13p6TeV_powheg-pythia8/AODSIM/133X_mcRun3_2024_realistic_v9-v3/2820000/27ec44a5-1e43-4073-b827-ca54c3d40e9e.root
        PFN : None
        PNN : T2_CH_CERN
        StageOutCommand : None
        ErrorCode : 60311
        ErrorType : GeneralStageOutFailure

Traceback: 

<@---------- WMException End ----------@>
```

### PR DESCRIPTION
**Pull request by todor-ivanov**
Fixes #11893 

#### Status
ready

#### Description
With the current  PR, we try to estimate the OS on the singularity container, where the job has landed at runtime.  

#### Is it backward compatible (if not, which system it affects?)
YES

#### Related PRs
None

#### External dependencies / deployment changes
None

### CODE REVIEW

**Comment by todor-ivanov** [comment]
and here are the test workflows for this patch: 
https://cmsweb-testbed.cern.ch/reqmgr2/fetch?rid=tivanov_ReReco_Run2022C_LumiMask_CleanupFixTest_v1_240213_172954_261
 
https://cmsweb-testbed.cern.ch/reqmgr2/fetch?rid=tivanov_ReReco_RunBlockWhite_CleanupFixTest_v1_240213_172947_3955

File: etc/submit_py3.sh [hunk 1]
```diff
@@ -58,7 +58,9 @@ PY3_FUTURE_VERSION=0.18.2
 # Saving START_TIME and when job finishes END_TIME.
 WMA_MIN_JOB_RUNTIMESECS=300
 START_TIME=$(date +%s)
-WMA_DEFAULT_OS=rhel7
+WMA_DEFAULT_OS=rhel8
+WMA_CURRENT_OS=rhel$(rpm --eval '%{rhel}')
+[[ $WMA_CURRENT_OS =~ ^rhel[789]?$ ]] || WMA_CURRENT_OS=$WMA_DEFAULT_OS
```
Comment (amaltaro) [inline etc/submit_py3.sh:63]: Shouldn't it support `rhel6` as well?

File: etc/submit_py3.sh [hunk 2]
```diff
@@ -142,10 +144,10 @@ echo "======== WMAgent COMP Python bootstrap starting at $(TZ=GMT date) ========
 
 # First, decide which COMP ScramArch to use based on the required OS and Architecture
 THIS_ARCH=`uname -m`  # if it's PowerPC, it returns `ppc64le`
-# if this job can run at any OS, then use rhel7 as default
+# if this job can run at any OS, then try to run it on the OS estimated at runtime
```
Comment (amaltaro) [inline etc/submit_py3.sh:147]: How about rephrasing it to "discovered" (instead of "estimated")? As this is what is actually happening.

**Review by amaltaro — CHANGES_REQUESTED** [review]
@todor-ivanov please find a couple of comments inline.
In addition, can you please amend the commit message and fix that typo? Thanks

File: etc/submit_py3.sh (hunk 1 above)
Comment (todor-ivanov) [reply etc/submit_py3.sh]: done

File: etc/submit_py3.sh (hunk 2 above)
Comment (todor-ivanov) [reply etc/submit_py3.sh]: done

**Review by amaltaro — APPROVED** [review]
These changes are looking good to me. Thanks for updating the commit message as well, Todor.

**Comment by amaltaro** [comment]
Can you please take care of the backporting and patching as well? We need to backport this PR to the branch `2.3.0_wmagent` and make a new release against that branch (2.3.0.2).

As previously discussed, we also need to patch all the agents connected to the production system. Note that this only affects the job wrapper, so there is no need to restart any service/components in the agent.

@germanfgv @LinaresToine could you please take care of the T0 agents? If you need any guidance, please let us know.

**Comment by todor-ivanov** [comment]
@amaltaro  All has been backported and new release created:  https://github.com/dmwm/WMCore/commits/2.3.0_wmagent/

**Comment by amaltaro** [comment]
Thank you, Todor. We have usually made the backport through another PR targetting the specific branch, instead of pushing the commit directly upstream.

I don't think there is any strong reason for doing it that way or this way, but if you feel like adding a short section with a procedure for backporting hot-fixes, I would suggest this wiki: https://github.com/dmwm/WMCore/wiki/TaggingAndReleasing#new-tagging-convention (well, the relevant in gitlab).

**Comment by todor-ivanov** [comment]
Hi @amaltaro 

I know the general procedure we usually follow. But this time, I decided to directly cherry-pick just the commit from the master branch to the one to be back ported. I think this keeps the repository history more clean. And avoids any eventual differences between the master branch and the branch to which the commit is backported. Also in the case of eventual conflicts (which may appear if in the meantime some code changes have accumulated on the same source files as the current patch), they will be resolved in the process of cherry-picking, which makes it local to the working tree of the person doing the operation, instead of the upstream repository during the merge of the additional PR. This again - helps keeping the history clean. Of course, we lack the additional PR, but that's fine with me - we can create it if we want of course. I have no strong opinion here either.

**Comment by amaltaro** [comment]
I like having the reference to the PR and the details that come with it, I guess that's why I always went with an extra PR against the particular branch. In addition, note that we can also cherry-pick - actually, this is the recommended way to keep meta-data intact - the master commit and provide it in a development branch against the particular wmagent/cmsweb branch. So, conflict resolution is the same between pushing upstream or pushing through a development branch.
