### PR TITLE
Limit number of rows returned from WorkQueue workRestrictions

### LINKED ISSUE #9670: WorkQueueManager timing out when pulling work from the parent queue
**Impact of the bug**
WMAgents

**Describe the bug**
Issue similar to: https://github.com/dmwm/WMCore/issues/9668
and especially: https://github.com/dmwm/WMCore/issues/9669

where, apparently, WorkQueueManager tries to pull all the GQEs sitting in Available status. Which is almost 400k at the moment and almost .5GB of data.

**How to reproduce it**
hundreds of thousands of docs Available in GQ

**Expected behavior**
The obvious one, it shouldn't crash the cycle.
Second, it should not pull all the documents at once (I was pretty sure it did NOT work this way... needs debugging).
And the whole functionality needs to be kept intacted.

**Additional context and error message**
WorkQueueManager traceback from vocms0256:
```
2020-04-30 15:55:28,388:140101196162816:INFO:BaseWorkerThread:WorkQueueManagerLocationPoller took 28.221 secs to execute
2020-04-30 15:56:12,339:140101213210368:ERROR:WorkQueueManagerWorkPoller:Unable to pull work from parent Error: (28, 'Operation timed out after 270000 milliseconds with 421693713 bytes received')
Traceback (most recent call last):
  File "/data/srv/wmagent/v1.3.3/sw/slc7_amd64_gcc630/cms/wmagent/1.3.3/lib/python2.7/site-packages/WMComponent/WorkQueueManager/WorkQueueManagerWorkPoller.py", line 101, in pullWork
    work = self.queue.pullWork()
  File "/data/srv/wmagent/v1.3.3/sw/slc7_amd64_gcc630/cms/wmagent/1.3.3/lib/python2.7/site-packages/WMCore/WorkQueue/WorkQueue.py", line 813, in pullWork
    work = self.getAvailableWorkfromParent(resources, jobCounts)
  File "/data/srv/wmagent/v1.3.3/sw/slc7_amd64_gcc630/cms/wmagent/1.3.3/lib/python2.7/site-packages/WMCore/WorkQueue/WorkQueue.py", line 791, in getAvailableWorkfromParent
    work, _, _ = self.parent_queue.availableWork(resources, jobCounts, self.params['Team'], numElems=numElems)
  File "/data/srv/wmagent/v1.3.3/sw/slc7_amd64_gcc630/cms/wmagent/1.3.3/lib/python2.7/site-packages/WMCore/WorkQueue/WorkQueueBackend.py", line 368, in availableWork
    result = self.db.loadList('WorkQueue', 'workRestrictions', 'availableByPriority', options)
  File "/data/srv/wmagent/v1.3.3/sw/slc7_amd64_gcc630/cms/wmagent/1.3.3/lib/python2.7/site-packages/WMCore/Database/CMSCouch.py", line 570, in loadList
    decode=False)
  File "/data/srv/wmagent/v1.3.3/sw/slc7_amd64_gcc630/cms/wmagent/1.3.3/lib/python2.7/site-packages/WMCore/Services/Requests.py", line 127, in get
    encode, decode, contentType)
  File "/data/srv/wmagent/v1.3.3/sw/slc7_amd64_gcc630/cms/wmagent/1.3.3/lib/python2.7/site-packages/WMCore/Database/CMSCouch.py", line 122, in makeRequest
    encode, decode, contentType)
  File "/data/srv/wmagent/v1.3.3/sw/slc7_amd64_gcc630/cms/wmagent/1.3.3/lib/python2.7/site-packages/WMCore/Services/Requests.py", line 165, in makeRequest
    result, response = self.makeRequest_pycurl(uri, data, verb, headers)
  File "/data/srv/wmagent/v1.3.3/sw/slc7_amd64_gcc630/cms/wmagent/1.3.3/lib/python2.7/site-packages/WMCore/Services/Requests.py", line 183, in makeRequest_pycurl
    ckey=ckey, cert=cert, capath=capath)
  File "/data/srv/wmagent/v1.3.3/sw/slc7_amd64_gcc630/cms/wmagent/1.3.3/lib/python2.7/site-packages/WMCore/Services/pycurl_manager.py", line 257, in request
    curl.perform()
error: (28, 'Operation timed out after 270000 milliseconds with 421693713 bytes received')

2020-04-30 15:56:12,339:140101213210368:INFO:WorkQueueManagerWorkPoller:Obtained 0 unit(s) of work
2020-04-30 15:56:12,420:140101213210368:INFO:WorkQueueManagerWorkPoller:Splitting new work
```

### PR DESCRIPTION
**Pull request by amaltaro**
Fixes #9670 

#### Status
not-tested

#### Description
Change the `workRestrictions` list function such that it can take a new query argument named: `num_elem`. This num_elem will be used to limit the amount of elements to be returned in the query. Different than the `limit` couchdb view query, which limits the amount of rows **passed** to the list function.
I have also updated the WorkQueueManager configuration `WorkPerCycle` to fetch up to 200 elements per cycle.

Besides that, made this procedure slightly more verbose.

#### Is it backward compatible (if not, which system it affects?)
NO (agents can only be patched once this has been deployed to CMSWEB production)

#### Related PRs
It's meant to superseed this temporary PR: https://github.com/dmwm/WMCore/pull/9671

#### External dependencies / deployment changes
none

### CODE REVIEW

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
I can't really make sense of the unit test errors in:
WMCore_t.WorkQueue_t.WorkQueue_t.WorkQueueTest.testProcessingWithContinuousSplitting

either the databases aren't fully synced, or `addWork` now behaves slightly different and tries to re-insert elements already inserted (even though I fail to see how these changes would affect that).

**Comment by amaltaro** [comment]
test this please

**Review by todor-ivanov — APPROVED** [review]
Looks good to me. Only one side comment/question, though. In case we are not fetching all the work queue elements at one go, do we somehow assure ourselves that those whose status fails to be updated (for any reason) are not sitting on top of the queue and are not repeatedly retried, pushing back new elements?

**Comment by amaltaro** [comment]
It seems to be working fine. If we push it to the global workqueue, we also need to backport this fix to all the agents and enable this feature on the agents at the same time CMSWEB upgrade happens.

File: src/couchapps/WorkQueue/lists/workRestrictions.js [hunk 1]
```diff
@@ -13,6 +13,13 @@ function(head, req) {
         return;
     }
 
+    try {
+        var num_elem = JSON.parse(req.query.num_elem);
+    } catch (ex) {
+        send('"Error parsing number of elements" ' +  req.query.num_elem);
```
Comment (amaltaro) [inline src/couchapps/WorkQueue/lists/workRestrictions.js:19]: @todor-ivanov to make it sort of backwards compatible, instead of raising an error here, we could set it to a large default value and move on. This way we do not need to backport this feature to the agents. Of course, in a later stage we need to clean this up. What do you think?

Comment (amaltaro) [reply src/couchapps/WorkQueue/lists/workRestrictions.js:19]: Just changed my mind, the sooner we get all the agents with this fix in, the safer we are against another avalanche of workflows and/or WQE.
