### PR TITLE
Failed jobs may not contain LogCollect key

### LINKED ISSUE #7008: Local couch raising "TypeError("logCollectStep.output.LogCollect is undefined", "undefined", 13)"
@ticoann Seangchan,

I've just found this problem in vocms0311 couch logs
```
[Thu, 28 Jul 2016 13:22:35 GMT] [info] [<0.619.0>] 127.0.0.1 - - POST /workqueue/_design/WorkQueue/_list/filter/elementsBySubscription?filter=%7B%22SubscriptionId%22%3A+2446%7D&idOnly=false&reduce=false&include_docs=true 200
[Thu, 28 Jul 2016 13:22:35 GMT] [info] [<0.379.0>] OS Process #Port<0.3931> Log :: function raised exception (new TypeError("logCollectStep.output.LogCollect is undefined", "undefined", 13)) with doc._id 3431270-0
[Thu, 28 Jul 2016 13:22:35 GMT] [info] [<0.632.0>] 127.0.0.1 - - PUT /wmagent_jobdump%2Fjobs/_design/JobDump/_update/stateTransition/3431849?oldstate=created&newstate=executing&location=T1_DE_KIT&timestamp=1469712149 201
```

which seems to be hitting couch quite often (it seems there are other cases as well).

If I got it right, the problem comes from this line:
https://github.com/dmwm/WMCore/blob/master/src/couchapps/FWJRDump/views/logArchivePerWorkflowTask/map.js#L13

which does not validate `LogCollect` key existence. Am I right?

Just in case, here is a json of the FJR mentioned above:
```
{u'_id': u'3431270-0',
 u'_rev': u'2-5ed8858af186eda961a2e712b8f72fef',
 u'archivestatus': u'uploaded',
 u'fwjr': {u'fallbackFiles': [],
           u'skippedFiles': [u'/store/unmerged/logs/prod/2016/7/27/pdmvserv_B2G-RunIISummer15wmLHEGS-00252_00128_v0__160725_202240_4742/Production/0000/0/ed15ea60-5399-11e6-95ba-001e67abef8c-145-0-logArchive.tar.gz',
                             u'/store/unmerged/logs/prod/2016/7/27/pdmvserv_B2G-RunIISummer15wmLHEGS-00252_00128_v0__160725_202240_4742/Production/0000/0/ed15ea60-5399-11e6-95ba-001e67abef8c-361-0-logArchive.tar.gz',
                             u'/store/unmerged/logs/prod/2016/7/27/pdmvserv_B2G-RunIISummer15wmLHEGS-00252_00128_v0__160725_202240_4742/Production/0000/0/ed15ea60-5399-11e6-95ba-001e67abef8c-291-0-logArchive.tar.gz',
                             u'/store/unmerged/logs/prod/2016/7/27/pdmvserv_B2G-RunIISummer15wmLHEGS-00252_00128_v0__160725_202240_4742/Production/0000/0/ed15ea60-5399-11e6-95ba-001e67abef8c-352-0-logArchive.tar.gz'],
           u'steps': {u'logCollect1': {u'analysis': {},
                                       u'cleanup': {},
                                       u'errors': [],
                                       u'input': {},
                                       u'logs': {},
                                       u'output': {u'analysis': []},
                                       u'parameters': {},
                                       u'performance': {u'cpu': {},
                                                        u'memory': {},
                                                        u'multicore': {},
                                                        u'storage': {}},
                                       u'site': u'T2_US_Purdue',
                                       u'start': 1469711471,
                                       u'status': 1,
                                       u'stop': None}},
           u'task': u'/pdmvserv_B2G-RunIISummer15wmLHEGS-00252_00128_v0__160725_202240_4742/Production/LogCollect'},
 u'jobid': 3431270,
 u'jobstate': u'jobfailed',
 u'jobtype': u'LogCollect',
 u'retrycount': 0,
 u'timestamp': 1469711833,
 u'type': u'fwjr'}
```

### PR DESCRIPTION
**Pull request by amaltaro**
Fixes #7008

@ticoann please review.

### CODE REVIEW

File: src/couchapps/FWJRDump/views/logArchivePerWorkflowTask/map.js [hunk 1]
```diff
@@ -8,10 +8,12 @@ function (doc) {
     taskType = task.slice(-1)[0];
     isLogCollect = taskType.indexOf('LogCollect');
     if (isLogCollect >= 0) {
-        if (null != doc.fwjr.steps.logCollect1) {
+        if (doc.fwjr.steps.logCollect1 != null) {
             logCollectStep = doc.fwjr.steps.logCollect1;
-            logArchivePFN = logCollectStep.output.LogCollect[0].lfn;
-            emit(doc.fwjr.task, logArchivePFN);
+            if (logCollectStep.output.LogCollect != undefined) {
```
Comment (ticoann) [inline src/couchapps/FWJRDump/views/logArchivePerWorkflowTask/map.js]: maybe we can do it combined condition

```
if ((doc.fwjr.steps.logCollect1 != null) && (logCollectStep.output.LogCollect != undefined))
```

**Comment by amaltaro** [comment]
Fixed under Seangchan's watch! @ticoann please review :-D

**Comment by ericvaandering** [comment]
This is still my stupidity that I have to fix. The pylint test fails if none of the files changed are python.
