### PR TITLE
Fix manage path in the restartComponent script

### LINKED ISSUE #11492: Script to restart components using the wrong path
**Impact of the bug**
WMAgent

**Describe the bug**
The script to restart components:
https://github.com/dmwm/WMCore/blob/master/deploy/restartComponent.sh

defined as a cronjob in the agent boxes, is actually unable to restart components because it has a wrong path to the `manage` script.

We received email notifications in the beginning of this week, and today once again. The reason those notifications keep coming is that the script fails to actually restart the component, thus triggering the same cycle over and over.

**How to reproduce it**
```
[cmsdataops@cmsgwms-submit3 current]$ /data/admin/wmagent/restartComponent.sh
```

**Expected behavior**
Fix those path in the script. Or just use it from the env.sh script.

**Additional context and error message**
None

### PR DESCRIPTION
**Pull request by amaltaro**
Fixes #11492 
Superseeds https://github.com/dmwm/WMCore/pull/11493

#### Status
ready

#### Description
Instead of redefining variables to be used in this script, just use those already defined in the `env.sh` script.
Fix the `$install` variable if needed (artifact from python2 vs python3 WMAgent).

#### Is it backward compatible (if not, which system it affects?)
YES

#### Related PRs
None

#### External dependencies / deployment changes
None

### CODE REVIEW

**Comment by amaltaro** [comment]
This proposal actually drops the `amtool`, from the PR that it superseeds. If we want to adopt amtool for such alerts - from outside CERN - then someone will have to follow this up with CMSMonitoring and CERN IT. But I suggest to deal with that in a different issue not to block this one.

**Comment by amaltaro** [comment]
This has been tested in the FNAL agent. 
Apologies for bypassing the review, but we definitely need to start this upgrade today.

File: deploy/restartComponent.sh [hunk 1]
```diff
@@ -1,18 +1,22 @@
...
+# Get a few environment variables in, like $install and $manage
+source /data/admin/wmagent/env.sh
+
 # Figure whether it's a python2 or python3 agent
-if [ -d "/data/srv/wmagent/current/install/wmagent" ]; then
-  WMA_PATH="/data/srv/wmagent/current/install/wmagent"
-else
-  WMA_PATH="/data/srv/wmagent/current/install/wmagentpy3"
+if [ ! -d "$install" ]; then
+  install="/data/srv/wmagent/current/install/wmagentpy3"
```
Comment (todor-ivanov) [inline deploy/restartComponent.sh:13]: I know the following component does not relate to this exact script (so no action expected - just a comment).
I think python3 is the de-facto only version we are going to support from now on... and we never plan to move back to py2 or to prolong any support of it.So we should think of getting rid of this  `py3` suffix.

File: deploy/restartComponent.sh [hunk 2]
```diff
@@ -22,9 +26,8 @@ for comp in $COMPONENTS; do
       exit 1
     fi
 
-    . /data/admin/wmagent/env.sh
     TAIL_LOG=`tail -n100 $COMPLOG`
-    $WMA_PATH/manage execute-agent wmcoreD --restart --components=$comp
+    $manage execute-agent wmcoreD --restart --components=$comp
```
Comment (todor-ivanov) [inline deploy/restartComponent.sh:30]: It is indeed better. It seems in the previous version this script must have been failing completely ....

**Review by todor-ivanov — COMMENTED** [review]
looks good

File: deploy/restartComponent.sh (hunk 1 above)
Comment (amaltaro) [reply deploy/restartComponent.sh:13]: Yes, I thought the same as well. The positive aspect of keeping this logic around is that it will ease the migration process to a new major python release. However, there is no release date for python4 neither certainty that it will be ever released.
