### PR TITLE
Fix python version for patchComponent.sh

### LINKED ISSUE #11271: Old python version for patchComponent.sh script
**Impact of the bug**
Auxiliary scripts

**Describe the bug**
While trying to patch a component (e.g. reqmgr2) in one of the testbed pods, I figured out  we have a wrong python version in the `patchComponent.sh` script at `bin`.

**How to reproduce it**
Try to patch any component with the broken script

**Expected behavior**
To have up to date python version in the auxiliary scripts
 
**Additional context and error message**
None

### PR DESCRIPTION
**Pull request by todor-ivanov**
Fixes #11271 

#### Status
ready

#### Description
Fixes old python version for `patchComponent.sh` auxiliary script, and also fixes the bad (deployment) patch in the usage example.

#### Is it backward compatible (if not, which system it affects?)
NO

#### Related PRs
None

#### External dependencies / deployment changes
None

### CODE REVIEW

File: bin/patchComponent.sh [hunk 1]
```diff
@@ -6,21 +6,23 @@ usage()
...
-    echo -ne "\t curl https://patch-diff.githubusercontent.com/raw/dmwm/deployment/pull/740.patch  | sudo ./patchComponent.sh (wmagent | reqmon | reqmgr2 | reqmgr2ms...)\n"
+    echo -ne "\t curl https://patch-diff.githubusercontent.com/raw/dmwm/WMCore/pull/11270.patch | sudo ./patchComponent.sh (wmagent | reqmon | reqmgr2 | reqmgr2ms...)\n"
     exit 1
 }
 
 # TODO: To check against a list of components
 component=$1
 [[ -z $component ]] && usage
 
+pythonVer="3.8"
```
Comment (vkuznet) [inline bin/patchComponent.sh:17]: @todor-ivanov , how about to make it more flexible here. Just read from env and put default value, e.g. 
```
pythonVer=${PYTHON_VERSION:-3.8}
```
This will make this script more flexible and allow you to define python version in environment, which may be useful in k8s, etc. This will also allow to change to new python version easily if it will be required.

**Review by vkuznet — CHANGES_REQUESTED** [review]

File: bin/patchComponent.sh (hunk 1 above)
Comment (todor-ivanov) [reply bin/patchComponent.sh:17]: Thanks @vkuznet that's  an excellent idea.

**Review by vkuznet — APPROVED** [review]

**Review by amaltaro — CHANGES_REQUESTED** [review]
@todor-ivanov I think this might actually use the python interpreter available at the system, instead of the one we use within WMCore services.

To make it simpler, I would suggest to actually remove the python version dependency, replacing code like `python$pythonVer` by `python*`. What do you think?

File: bin/patchComponent.sh [hunk 2]
```diff
@@ -18,9 +18,9 @@ echo "Patching component: $component"
 
 if [[ $component == "wmagent" ]]
 then
-    rootDir=/data/srv/$component/current/apps.sw/$component/lib/python2.7/site-packages
+    rootDir=/data/srv/$component/current/apps.sw/$component/lib/python*/site-packages
```
Comment (vkuznet) [inline bin/patchComponent.sh:21]: I don't like it. Instead, just setup above the variable with python version by using python itself, e.g.
```
pver=`python -V | awk '{z=split($2,a,"."); print ""a[1]"."a[2]""}'`
```
which will print 3.9 or something and then use it in your rootDir

**Review by vkuznet — APPROVED** [review]

File: bin/patchComponent.sh (hunk 2 above)
Comment (amaltaro) [reply bin/patchComponent.sh:21]: It will not work! See the output from one pod:
```
blah@blah:~ $ kubectl exec -n dmwm -it reqmgr2-fc89869d-28pcw bash
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
Defaulted container "reqmgr2" out of: reqmgr2, reqmgr2-filebeat
[_reqmgr2@reqmgr2-fc89869d-28pcw data]$ python -V
Python 2.7.5
[_reqmgr2@reqmgr2-fc89869d-28pcw data]$ python3 -V
bash: python3: command not found
```

We deploy our services under a given python version, so there shouldn't be two names or anything like that in that path. I see no problems with the wildcard to avoid depending on the python version for this patching.

**Comment by todor-ivanov** [comment]
This is not that important issue, we should not waste time in changing multiple times a single line. 
and moreover this one is working already fine enough. I've tested it already directly with production agents, so it is fine. 
I am merging this now @amaltaro
