### PR TITLE
Split patch files by source files edited && Apply them separately

### LINKED ISSUE #12345: AUX: bin/patchComponent.sh cannot handle top level files
**Impact of the bug**
Auxiliary scripts

**Describe the bug**
Whenever one uses the `bin/patchComponent.sh` script with a patch which touches any of the top level files in our Code base (anything above `WMCore/src/python` or  `WMCore/test/python`) it fails to apply the patch.  

**How to reproduce it**
Try to patch an agent with a patch which modifies anything above `WMCore/src/python` in our code base 

**Expected behavior**
to be able to find the proper destination and patch the component

**Additional context and error message**
```
cmst1@vocms266:data $ docker exec -u root -it wmagent /bin/bash 
(WMAgent-2.3.4.4) [root@vocms266:data]# ./patchComponent.sh 12302
...


INFO: ----------------- Currently applying patch: 12302 -----------------
INFO: cat /tmp/12302.patch | patch -t --verbose -b --version-control=numbered -d /usr/local/lib/python3.8/site-packages -p3
Hmm...  Looks like a unified diff to me...
can't find file to patch at input line 19
Perhaps you used the wrong -p or --strip option?
```
And opening the patch, here is what is on line 19: 
```
...
     15 diff --git a/bin/wmcoreD b/bin/wmcoreD
     16 index 40c773adb5..1415541df9 100755
     17 --- a/bin/wmcoreD
     18 +++ b/bin/wmcoreD
     19 @@ -40,7 +40,10 @@ import os
...
```

### PR DESCRIPTION
**Pull request by todor-ivanov**
Fixes #12345 

#### Status
Ready

#### Description
With the current change all patch files provided to the script `patchComponent.sh`  either through `<PR number>` or `<patchFile at the command line>` or `<stdin>` are split in separate  `*.patch` files according to the source  file edited  in the original patch file and are applied separately, preserving the order they have been provided. This way depending on the source file we can properly determine all `patch` command parameters like `stripLevel` and `destination` so that we  can properly handle any file distributed with our packages not only those coming from `WMCore/src/python`

For this patch files splitting, the standard command `csplit` is used. It is distributed with the `coreutils` package, which is available at all our service  instances, so no new dependency is introduced with this PR

**Validation steps:**

here is how I was  testing this change while developing (I chose two related PRs both updating overlapping sets of source files including some toplevel source files as well) :

* WMAgent@docker:
```
(WMAgent-2.3.10rc17) [root@vocms0290:data]# ./patchComponent.sh 12302 12312 2>&1 |tee /tmp/12302.log
```
* WMAgent@Venv:

```
(WMAgent.venv3) [cmst1@vocms0290 WMCore]$ ./patchComponent.sh 12302 12312 2>&1 |tee /tmp/12302.log
```

#### Is it backward compatible (if not, which system it affects?)
YES

#### Related PRs
None

#### External dependencies / deployment changes
None

### CODE REVIEW

File: bin/patchComponent.sh [hunk 1]
```diff
@@ -138,12 +246,12 @@ _zeroCodeBase() {
         fileDir=`dirname $file`
         # Create the file path if missing
         mkdir -p $pythonLibPath/$fileDir
-        echo INFO: orig: https://raw.githubusercontent.com/dmwm/WMCore/$srcBranch/src/python/$file
-        echo INFO: dest: $pythonLibPath/$file
-        curl -f https://raw.githubusercontent.com/dmwm/WMCore/$srcBranch/src/python/$file  -o $pythonLibPath/$file || {
-            echo INFO: file: $file missing at the origin.
-            echo INFO: Seems to be a new file for the curren patch.
-            echo INFO: Removing it from the destination as well!
+        echo INFO: $FUNCNAME: orig: https://raw.githubusercontent.com/dmwm/WMCore/$srcBranch/$file
```
Comment (vkuznet) [inline bin/patchComponent.sh:249]: Todor, you are using in many places this URL and it would be more appropriate to put it at the top of the script as global variable like:
```
WMURL=https://raw.githubusercontent.com/dmwm/WMCore

...
# and then use iecho INFO: $FUNCNAME: orig: $WMURL/$srcBranch/$filet like

```

File: bin/patchComponent.sh [hunk 2]
```diff
@@ -157,46 +265,73 @@ _zeroCodeBase() {
...
+        echo "INFO: $FUNCNAME: Patching WMCore code with PRs: $patchList"
     fi
     for patchNum in $patchList
     do
         patchFile=/tmp/$patchNum.patch
-        patchFileList="$patchFileList $patchFile"
-        echo "INFO: Downloading a temporary patchFile at: $patchFile"
-        curl https://patch-diff.githubusercontent.com/raw/dmwm/WMCore/pull/$patchNum.patch -o $patchFile
+        echo "INFO: $FUNCNAME: Downloading a temporary patchFile at: $patchFile"
+        curl https://patch-diff.githubusercontent.com/raw/dmwm/WMCore/pull/$patchNum.patch -o $patchFile || {
```
Comment (vkuznet) [inline bin/patchComponent.sh:323]: If you will define WMURL then move the patch url as global variable too.

**Review by vkuznet — CHANGES_REQUESTED** [review]
Todor, all changes look solid to me and I trust that you tested them in your environment. I only request to move to global variables github URLs. And, in fact, you can print them out also before running any action of the script that it will be clear where we get sources and patches.

**Comment by todor-ivanov** [comment]
hi @vkuznet  I addressed your comments. Could you take another look, please?

**Review by vkuznet — APPROVED** [review]

**Comment by todor-ivanov** [comment]
hi @amaltaro, Done.
